id: P18F1AAB3
initial_creation_type: ocr
source_metadata:
  volumes:
    c1021c1375e54be2a770f5cce7e3bc28:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: གཏོར་མའི་ཆོ་ག།
      total_pages: 2069
      volume_number: 5
